version: '3.7'

services: 

  portfolio:
    image: tbichse/portfolio:1.0-ubuntu
    container_name: portfolio 
    stdin_open: true
    ports: 
      - 8081:3000

networks:
  default:
    external:
      name: nginxproxy
