import { Card, CardContent, CardHeader, CardMedia } from '@mui/material';
import Head from 'next/head'
import styles from '../styles/Projects.module.css';

export default function Project() {
  return (
    <>
      <Head>
        <title>Tucker Bichsel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Projects</h1>
        <div className={styles.projects}>
          <Card className={styles.projectCard}>
            <CardHeader className={styles.cardHeader}
              title="DVC Calculator" />
            <CardMedia className={styles.cardImage}
              component="img"
              image="/dvcCalc.png"
              alt="DVC Calc"
            />
            <CardContent>This is a calculator to plan disney trips. <a className='link' href="https://dvc-calc.tucker-dev.com">DVC Calculator</a></CardContent>
          </Card>
          <Card className={styles.projectCard}>
            <CardHeader className={styles.cardHeader}
              title="Memory Social" />
            <CardMedia className={styles.cardImage}
              component="img"
              image="/memorySocial.png"
              alt="Merory Social"
            />
            <CardContent>This is a social media application where the posts do not live forever and instead turn into memories. <a className='link' href="https://memory-social.tucker-dev.com">Memory Social</a></CardContent>
          </Card>
        </div>
        <div className={styles.projectFooter}></div>
      </main>
    </>
  )
}
